# Generated by Django 6.1 on 2026-08-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='seller_name',
            field=models.CharField(default='Demo Seller', max_length=150),
        ),
    ]
