# Generated by Django 6.1 on 2026-08-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_productlisting_seller_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='availability',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock')], default='in_stock', max_length=20),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='category',
            field=models.CharField(default='Books', max_length=50),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
