# Generated by Django 6.1 on 2026-08-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='listings/'),
        ),
    ]
