# Generated by Django 6.1 on 2026-08-12 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlisting',
            name='image',
        ),
    ]
